"""folowers

Revision ID: 58444c56dea7
Revises: 47f48360b751
Create Date: 2019-02-12 21:30:59.913728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58444c56dea7'
down_revision = '47f48360b751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
