"""..

Revision ID: 750c44ecaa2a
Revises: 108cb24da553
Create Date: 2019-05-04 19:42:48.123070

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '750c44ecaa2a'
down_revision = '108cb24da553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body_html', sa.Text(), nullable=True))
    op.drop_column('post', 'bod_html')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('bod_html', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.drop_column('post', 'body_html')
    # ### end Alembic commands ###
