"""isvalid

Revision ID: a185b34a9bfd
Revises: 750c44ecaa2a
Create Date: 2019-05-06 23:51:41.180941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a185b34a9bfd'
down_revision = '750c44ecaa2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_roles_default', table_name='roles')
    # op.drop_index('name', table_name='roles')
    # op.drop_table('roles')
    op.add_column('post', sa.Column('isvalid', sa.Boolean(), nullable=True))
    # op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    # op.drop_column('user', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('user', sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # op.create_foreign_key('user_ibfk_1', 'user', 'roles', ['role_id'], ['id'])
    # op.drop_column('post', 'isvalid')
    # op.create_table('roles',
    # sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    # sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True),
    # sa.Column('default', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    # sa.Column('permissinons', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_collate='utf8mb4_unicode_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_index('name', 'roles', ['name'], unique=True)
    # op.create_index('ix_roles_default', 'roles', ['default'], unique=False)
    # ### end Alembic commands ###
