"""..

Revision ID: d4b3ee58d47f
Revises: 293834b225c2
Create Date: 2019-05-06 23:59:47.343425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4b3ee58d47f'
down_revision = '293834b225c2'
branch_labels = None
depends_on = None


def upgrade():
    # pass
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isvalid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('isvalid')

